version: '3.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main-basicauth}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=lambda,apigateway,s3,cloudformation,sts,iam,route53,dynamodb
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"