
service: basicauth
plugins:
 - serverless-localstack
custom:
  localstack:
    debug: true
    stages:
      - local
      - dev
    endpointFile: my_endpoints.json

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x


functions:
  mccbasicAuth:
    handler: handler.basicAuth
    events:
      - http:
          method: post
          path: /basicAuth